# Script mode: writes a C++ source file with the current git revision.
#
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<file.cpp> -P GitRevision.cmake
#
# Runs on every build. The file is only rewritten when the revision changes, so nothing recompiles needlessly.
# Outside a git checkout (source archive) the revision is "unknown".

set(_revision "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -c "safe.directory=${SOURCE_DIR}" describe --always --dirty --abbrev=10 --exclude=*
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE _described
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _result)
  if(_result EQUAL 0 AND _described MATCHES "^[0-9a-f]+(-dirty)?$")
    set(_revision "${_described}")
  endif()
endif()

set(_content "// Generated by cmake/GitRevision.cmake. Do not edit.
namespace cloudscope::detail {
extern const char* const kGitRevision;
const char* const kGitRevision = \"${_revision}\";
}  // namespace cloudscope::detail
")

set(_previous "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _previous)
endif()
if(NOT _content STREQUAL _previous)
  file(WRITE "${OUTPUT}" "${_content}")
endif()
